// lib/communitiesData.ts
import { CommunityData } from "@/types";

export const communitiesData: CommunityData[] = [
	{
		id: "athletes",
		name: "Athletes Community",
		slug: "athletes",
		icon: "🏃",
		tagline: "Excellence in Motion",
		description:
			"A vibrant community of sports professionals, athletes, coaches, and sports enthusiasts across Africa. From Olympic champions to weekend warriors, we unite to celebrate athletic excellence and promote sports development across the continent.",
		color: "#EF4444",
		established: "2020",
		stats: {
			members: "850K+",
			professionals: "125K+",
			companies: "15K+",
			jobs: "45K+",
			events: "500+",
			projects: "180+",
		},
		keyAreas: [
			"Professional Sports",
			"Sports Medicine & Science",
			"Athletic Training",
			"Sports Management",
			"Youth Development",
			"Sports Technology",
			"Nutrition & Fitness",
			"Sports Marketing",
		],
		benefits: [
			"Access to professional training programs",
			"Networking with elite athletes and coaches",
			"Sports scholarship opportunities",
			"Career transition support",
			"Equipment and gear discounts",
			"Sports science resources",
			"Mentorship programs",
			"International competition connections",
		],
		requirements: [
			"Active involvement in sports (any level)",
			"Commitment to athletic excellence",
			"Respect for fair play and sportsmanship",
			"Willingness to mentor upcoming athletes",
		],
		events: [
			{
				id: "ae-1",
				title: "Pan-African Sports Summit 2025",
				type: "conference",
				date: "2025-03-15",
				time: "09:00",
				duration: "3 days",
				location: "hybrid",
				description:
					"Annual gathering of Africa's top athletes, coaches, and sports administrators to discuss the future of African sports.",
				speakers: ["Olympic Champions", "Sports Ministers", "IOC Representatives"],
				capacity: 2000,
				registered: 1850,
				status: "upcoming",
			},
			{
				id: "ae-2",
				title: "Sports Science & Technology Workshop",
				type: "workshop",
				date: "2025-02-20",
				time: "14:00",
				duration: "4 hours",
				location: "virtual",
				description: "Latest innovations in sports technology, performance analysis, and injury prevention.",
				capacity: 500,
				registered: 420,
				status: "upcoming",
			},
			{
				id: "ae-3",
				title: "Youth Athletics Development Webinar",
				type: "webinar",
				date: "2025-02-10",
				time: "16:00",
				duration: "90 minutes",
				location: "virtual",
				description: "Strategies for identifying and nurturing young athletic talent across Africa.",
				capacity: 1000,
				registered: 850,
				status: "upcoming",
			},
		],
		leaders: [
			{
				id: "al-1",
				name: "Eliud Kipchoge",
				position: "Community Ambassador",
				company: "Olympic Champion",
				expertise: ["Marathon Running", "Mental Training", "Performance Optimization"],
				bio: "World record holder and two-time Olympic marathon champion leading initiatives to develop distance running across Africa.",
				achievements: [
					"First human to run marathon under 2 hours",
					"Two-time Olympic marathon gold medalist",
					"Four-time London Marathon winner",
					"Established running academies across Kenya",
				],
				socialLinks: {
					linkedin: "eliud-kipchoge",
					twitter: "@EliudKipchoge",
				},
			},
			{
				id: "al-2",
				name: "Dr. Benita Fitzgerald Mosley",
				position: "Sports Development Director",
				company: "African Sports Medicine Institute",
				expertise: ["Sports Medicine", "Athletic Development", "Olympic Programs"],
				bio: "Former Olympic champion and sports administrator dedicated to advancing sports science and athlete welfare in Africa.",
				achievements: [
					"Olympic gold medalist in hurdles",
					"CEO of Laureus Sport for Good Foundation",
					"Pioneer in African sports medicine",
					"Developed athlete scholarship programs",
				],
			},
		],
		resources: [
			{
				id: "ar-1",
				title: "Athletic Training Manual",
				type: "guide",
				description: "Comprehensive guide to modern athletic training methods and techniques.",
				category: "Training",
				difficulty: "intermediate",
				downloadCount: 15000,
				rating: 4.8,
			},
			{
				id: "ar-2",
				title: "Sports Nutrition Planner",
				type: "tool",
				description: "Interactive tool for planning optimal nutrition for different sports and training phases.",
				category: "Nutrition",
				difficulty: "beginner",
				downloadCount: 22000,
				rating: 4.7,
			},
			{
				id: "ar-3",
				title: "Injury Prevention Course",
				type: "course",
				description: "Online course covering injury prevention strategies for various sports.",
				category: "Health",
				difficulty: "intermediate",
				downloadCount: 8500,
				rating: 4.9,
			},
		],
		successStories: [
			{
				id: "as-1",
				memberName: "Sarah Atcho",
				profession: "Sprint Coach",
				company: "Swiss Athletics Federation",
				story: "Through JFAN's Athletes Community, I connected with international coaching networks and advanced training methodologies that transformed my coaching approach.",
				achievement: "Coached 5 athletes to Olympic qualification, established training academy in Switzerland",
				beforeAfter: {
					before: "Local club coach with limited international exposure",
					after: "International sprint coach with Olympic-level athletes",
				},
				year: "2023",
			},
			{
				id: "as-2",
				memberName: "Mutaz Essa Barshim",
				profession: "High Jump Champion",
				company: "Qatar Athletic Federation",
				story: "The community's mentorship program helped me transition from athlete to coach and sports administrator.",
				achievement: "Olympic gold medalist, now developing high jump programs across Africa",
				beforeAfter: {
					before: "Focused solely on personal athletic performance",
					after: "Leading sports development initiatives across multiple countries",
				},
				year: "2024",
			},
		],
		partnerships: [
			"International Olympic Committee (IOC)",
			"African Union Sports Council",
			"FIFA African Confederation",
			"Commonwealth Games Federation",
			"Laureus Sport for Good Foundation",
		],
		initiatives: [
			{
				id: "ai-1",
				title: "Olympic Dream Academy",
				description: "Identifying and developing young athletes with Olympic potential across Africa.",
				status: "active",
				impact: "500+ young athletes in training programs",
				participants: "2000+",
				startDate: "2021-06-01",
			},
			{
				id: "ai-2",
				title: "Sports Science Innovation Lab",
				description: "Research and development of sports technology solutions tailored for African athletes.",
				status: "active",
				impact: "15 innovative products developed",
				participants: "150+",
				startDate: "2022-01-15",
			},
		],
		futureGoals: [
			"Establish sports academies in all 55 African countries",
			"Create pathway for 1000+ African athletes to international competitions",
			"Develop world-class sports medicine facilities across the continent",
			"Launch African Sports Technology Innovation Hub",
		],
	},
	{
		id: "creative",
		name: "Creative Community",
		slug: "creative",
		icon: "🎨",
		tagline: "Creativity Without Boundaries",
		description:
			"A dynamic ecosystem of artists, designers, creators, and cultural innovators from across Africa and the diaspora. We celebrate African creativity while building bridges to global markets and opportunities.",
		color: "#8B5CF6",
		established: "2020",
		stats: {
			members: "1.2M+",
			professionals: "180K+",
			companies: "25K+",
			jobs: "75K+",
			events: "800+",
			projects: "350+",
		},
		keyAreas: [
			"Visual Arts & Design",
			"Music & Audio Production",
			"Film & Video Production",
			"Digital Media & Animation",
			"Fashion & Textiles",
			"Literature & Publishing",
			"Gaming & Interactive Media",
			"Cultural Heritage & Arts",
		],
		benefits: [
			"Global marketplace access for creative works",
			"Collaborative project opportunities",
			"Skill development workshops and masterclasses",
			"Intellectual property protection guidance",
			"Funding and grant opportunities",
			"International exhibition and showcase platforms",
			"Mentorship from industry leaders",
			"Creative tools and software discounts",
		],
		requirements: [
			"Active creative practice or interest",
			"Portfolio of creative work (any medium)",
			"Respect for intellectual property",
			"Commitment to supporting fellow creatives",
		],
		events: [
			{
				id: "ce-1",
				title: "African Creative Economy Summit",
				type: "conference",
				date: "2025-04-22",
				time: "10:00",
				duration: "2 days",
				location: "hybrid",
				description: "Exploring the business of creativity and cultural industries across Africa.",
				speakers: ["Grammy Winners", "Film Directors", "Fashion Designers"],
				capacity: 3000,
				registered: 2650,
				status: "upcoming",
			},
			{
				id: "ce-2",
				title: "Digital Art & NFT Workshop",
				type: "workshop",
				date: "2025-03-08",
				time: "15:00",
				duration: "6 hours",
				location: "virtual",
				description: "Creating, marketing, and selling digital art in the Web3 era.",
				capacity: 300,
				registered: 285,
				status: "upcoming",
			},
			{
				id: "ce-3",
				title: "Music Production Masterclass",
				type: "workshop",
				date: "2025-02-28",
				time: "18:00",
				duration: "3 hours",
				location: "virtual",
				description: "Advanced techniques in music production with Grammy-winning producers.",
				capacity: 200,
				registered: 195,
				status: "upcoming",
			},
		],
		leaders: [
			{
				id: "cl-1",
				name: "Burna Boy",
				position: "Music Ambassador",
				company: "Grammy Winner",
				expertise: ["Music Production", "International Marketing", "Cultural Fusion"],
				bio: "Grammy-winning artist championing African music globally and mentoring emerging artists through JFAN's platform.",
				achievements: [
					"Grammy Award winner for Best Global Music Album",
					"Multiple platinum albums worldwide",
					"Advocate for African music industry development",
					"Mentor to 100+ emerging artists",
				],
				socialLinks: {
					twitter: "@burnaboy",
					website: "burnaboy.com",
				},
			},
			{
				id: "cl-2",
				name: "Aida Muluneh",
				position: "Visual Arts Director",
				company: "Contemporary African Art Collective",
				expertise: ["Photography", "Visual Storytelling", "Cultural Documentation"],
				bio: "Internationally acclaimed photographer and curator promoting contemporary African visual arts globally.",
				achievements: [
					"Exhibited in major galleries worldwide",
					"Founded African photography festival",
					"Mentor to emerging African photographers",
					"Cultural ambassador for African visual arts",
				],
			},
		],
		resources: [
			{
				id: "cr-1",
				title: "Creative Business Toolkit",
				type: "guide",
				description: "Complete guide to building and scaling a creative business in Africa.",
				category: "Business",
				difficulty: "intermediate",
				downloadCount: 35000,
				rating: 4.9,
			},
			{
				id: "cr-2",
				title: "Digital Art Creation Suite",
				type: "tool",
				description: "Collection of digital brushes, textures, and templates for African-inspired art.",
				category: "Design",
				difficulty: "beginner",
				downloadCount: 50000,
				rating: 4.8,
			},
			{
				id: "cr-3",
				title: "Music Production Masterclass Series",
				type: "course",
				description: "16-week comprehensive course on modern music production techniques.",
				category: "Music",
				difficulty: "advanced",
				downloadCount: 12000,
				rating: 4.9,
			},
		],
		successStories: [
			{
				id: "cs-1",
				memberName: "Kwame Asante",
				profession: "Fashion Designer",
				company: "Asante Couture",
				story: "JFAN's Creative Community connected me with international buyers and helped me showcase at Paris Fashion Week.",
				achievement: "Fashion line now sold in 15 countries, featured in Vogue Africa",
				beforeAfter: {
					before: "Local tailor with limited market reach",
					after: "International fashion brand with global recognition",
				},
				year: "2023",
			},
			{
				id: "cs-2",
				memberName: "Amara Okafor",
				profession: "Film Director",
				company: "Nollywood Plus Productions",
				story: "The community's film network helped me secure funding and distribution for my debut feature film.",
				achievement: "Film premiered at Cannes, won 3 African film awards, secured Netflix deal",
				beforeAfter: {
					before: "Independent filmmaker struggling with funding",
					after: "Award-winning director with international distribution deals",
				},
				year: "2024",
			},
		],
		partnerships: [
			"UNESCO Creative Cities Network",
			"British Council Arts",
			"Goethe Institut",
			"Alliance Française",
			"Netflix Africa Creative Equity Fund",
		],
		initiatives: [
			{
				id: "ci-1",
				title: "African Digital Arts Incubator",
				description: "Supporting digital artists and creators with tools, training, and market access.",
				status: "active",
				impact: "2000+ digital artists supported, $5M in creator earnings",
				participants: "5000+",
				startDate: "2021-09-01",
			},
			{
				id: "ci-2",
				title: "Creative Heritage Preservation Project",
				description: "Digitizing and preserving traditional African art forms and cultural practices.",
				status: "active",
				impact: "500+ cultural artifacts digitized, 50+ traditional practices documented",
				participants: "200+",
				startDate: "2022-03-01",
			},
		],
		futureGoals: [
			"Create Africa's largest creative marketplace platform",
			"Establish creative hubs in 25 major African cities",
			"Generate $1B+ in revenue for African creators by 2026",
			"Launch African Creative Industries Development Fund",
		],
	},
	{
		id: "entrepreneurship",
		name: "Entrepreneurship Community",
		slug: "entrepreneurship",
		icon: "💼",
		tagline: "Building Africa's Future",
		description:
			"A powerhouse network of entrepreneurs, business leaders, innovators, and changemakers driving economic transformation across Africa. From startups to established enterprises, we're building Africa's entrepreneurial ecosystem.",
		color: "#F59E0B",
		established: "2020",
		stats: {
			members: "2.1M+",
			professionals: "350K+",
			companies: "85K+",
			jobs: "425K+",
			events: "1200+",
			projects: "750+",
		},
		keyAreas: [
			"Technology Startups",
			"Social Entrepreneurship",
			"Agriculture & AgriTech",
			"Financial Services & FinTech",
			"Healthcare Innovation",
			"Clean Energy & Sustainability",
			"Manufacturing & Industry 4.0",
			"E-commerce & Digital Services",
		],
		benefits: [
			"Access to funding and investment networks",
			"Mentorship from successful entrepreneurs",
			"Business development workshops and accelerators",
			"Market research and intelligence",
			"Networking with potential partners and customers",
			"Legal and regulatory guidance",
			"International market entry support",
			"Technology and innovation resources",
		],
		requirements: [
			"Active business or startup venture",
			"Commitment to ethical business practices",
			"Willingness to mentor other entrepreneurs",
			"Focus on positive impact and growth",
		],
		events: [
			{
				id: "ee-1",
				title: "Africa Startup Summit 2025",
				type: "conference",
				date: "2025-05-10",
				time: "08:00",
				duration: "3 days",
				location: "hybrid",
				description: "Africa's largest gathering of entrepreneurs, investors, and ecosystem builders.",
				speakers: ["Unicorn Founders", "Venture Capitalists", "Government Ministers"],
				capacity: 5000,
				registered: 4200,
				status: "upcoming",
			},
			{
				id: "ee-2",
				title: "Fintech Innovation Hackathon",
				type: "hackathon",
				date: "2025-03-20",
				time: "09:00",
				duration: "48 hours",
				location: "hybrid",
				description: "Building the next generation of African fintech solutions.",
				capacity: 1000,
				registered: 850,
				status: "upcoming",
			},
		],
		leaders: [
			{
				id: "el-1",
				name: "Dr. Rebecca Enonchong",
				position: "Tech Entrepreneurship Lead",
				company: "AppsTech CEO",
				expertise: ["Technology", "Venture Capital", "Digital Transformation"],
				bio: "Serial entrepreneur and investor championing African tech ecosystem development and women in technology.",
				achievements: [
					"Built multiple successful tech companies",
					"Advisor to African governments on digital strategy",
					"Investor in 50+ African startups",
					"Champion of women in tech initiatives",
				],
				socialLinks: {
					linkedin: "rebecca-enonchong",
					twitter: "@africatechie",
				},
			},
		],
		resources: [
			{
				id: "er-1",
				title: "Startup Funding Guide",
				type: "guide",
				description: "Comprehensive guide to raising capital for African startups.",
				category: "Funding",
				difficulty: "intermediate",
				downloadCount: 45000,
				rating: 4.8,
			},
			{
				id: "er-2",
				title: "Business Plan Template",
				type: "template",
				description: "Professional business plan template optimized for African markets.",
				category: "Planning",
				difficulty: "beginner",
				downloadCount: 75000,
				rating: 4.7,
			},
		],
		successStories: [
			{
				id: "es-1",
				memberName: "Sim Shagaya",
				profession: "E-commerce Entrepreneur",
				company: "Konga & uLesson Founder",
				story: "JFAN's network helped me scale my e-commerce platform and later launch EdTech solutions across Africa.",
				achievement: "Built Nigeria's largest e-commerce platform, raised $50M+ for EdTech startup",
				beforeAfter: {
					before: "Traditional retail business owner",
					after: "Serial entrepreneur with multiple successful exits",
				},
				year: "2023",
			},
		],
		partnerships: [
			"African Development Bank",
			"World Bank IFC",
			"Tony Elumelu Foundation",
			"Mastercard Foundation",
			"Google for Startups Africa",
		],
		initiatives: [
			{
				id: "ei-1",
				title: "African Startup Accelerator Network",
				description: "Pan-African accelerator program supporting early-stage startups across all sectors.",
				status: "active",
				impact: "500+ startups accelerated, $200M+ raised",
				participants: "2000+",
				startDate: "2021-01-01",
			},
		],
		futureGoals: [
			"Create Africa's first $1B venture capital fund",
			"Support 10,000+ new startups by 2026",
			"Establish innovation hubs in all 55 African countries",
			"Generate 1M+ jobs through supported enterprises",
		],
	},
	{
		id: "services",
		name: "Services Community",
		slug: "services",
		icon: "🔧",
		tagline: "Excellence in Service",
		description:
			"A comprehensive network of service providers, skilled professionals, and technical experts across all industries. From consultants to technicians, we're the backbone of Africa's service economy.",
		color: "#06B6D4",
		established: "2020",
		stats: {
			members: "3.5M+",
			professionals: "580K+",
			companies: "125K+",
			jobs: "650K+",
			events: "2000+",
			projects: "1200+",
		},
		keyAreas: [
			"Professional Services",
			"Technical & Engineering Services",
			"Healthcare & Medical Services",
			"Education & Training Services",
			"Financial & Legal Services",
			"Digital & IT Services",
			"Maintenance & Repair Services",
			"Hospitality & Tourism Services",
		],
		benefits: [
			"Professional certification and accreditation",
			"Skills development and upskilling programs",
			"Quality standards and best practices",
			"Client referral network",
			"Industry-specific training and resources",
			"Professional insurance and protection",
			"International market opportunities",
			"Peer-to-peer learning and support",
		],
		requirements: [
			"Professional service offering or expertise",
			"Commitment to quality and ethical standards",
			"Willingness to share knowledge and mentor others",
			"Continuous professional development",
		],
		events: [
			{
				id: "se-1",
				title: "Professional Services Excellence Summit",
				type: "conference",
				date: "2025-06-15",
				time: "09:00",
				duration: "2 days",
				location: "hybrid",
				description: "Elevating standards and innovation in professional services across Africa.",
				capacity: 2500,
				registered: 2100,
				status: "upcoming",
			},
		],
		leaders: [
			{
				id: "sl-1",
				name: "Prof. Yemi Osinbajo",
				position: "Professional Services Advisory Board",
				company: "Former Vice President of Nigeria",
				expertise: ["Legal Services", "Public Policy", "Governance"],
				bio: "Distinguished lawyer and policy expert advancing professional services standards across Africa.",
				achievements: [
					"Senior Advocate of Nigeria",
					"Former Vice President of Nigeria",
					"Professor of Law for over 20 years",
					"Legal reform advocate across Africa",
				],
			},
		],
		resources: [
			{
				id: "sr-1",
				title: "Service Excellence Framework",
				type: "guide",
				description: "Comprehensive framework for delivering world-class professional services.",
				category: "Quality",
				difficulty: "intermediate",
				downloadCount: 30000,
				rating: 4.8,
			},
		],
		successStories: [
			{
				id: "ss-1",
				memberName: "Dr. Akinwumi Adesina",
				profession: "Development Finance Expert",
				company: "African Development Bank",
				story: "Through JFAN's services network, I connected with development finance experts across Africa to drive agricultural transformation.",
				achievement: "Led $25B+ in development financing, transformed agricultural value chains across 20+ countries",
				beforeAfter: {
					before: "Academic researcher with policy ideas",
					after: "Leading continental development finance institution",
				},
				year: "2024",
			},
		],
		partnerships: [
			"Professional Bodies across Africa",
			"International Standards Organization",
			"World Trade Organization",
			"African Continental Free Trade Area",
			"International Labour Organization",
		],
		initiatives: [
			{
				id: "si-1",
				title: "African Professional Standards Initiative",
				description: "Harmonizing and elevating professional standards across African countries.",
				status: "active",
				impact: "50+ professional standards developed, 100K+ professionals certified",
				participants: "500+",
				startDate: "2021-04-01",
			},
		],
		futureGoals: [
			"Establish unified African professional accreditation system",
			"Create cross-border service delivery framework",
			"Develop 2M+ skilled service professionals by 2026",
			"Launch African Services Export Promotion Agency",
		],
	},
	{
		id: "enablement",
		name: "Enablement Community",
		slug: "enablement",
		icon: "🤝",
		tagline: "Empowering Success Together",
		description:
			"A supportive ecosystem of mentors, coaches, advisors, and champions dedicated to enabling others' success. We are the connectors, facilitators, and supporters who make dreams achievable.",
		color: "#10B981",
		established: "2020",
		stats: {
			members: "950K+",
			professionals: "165K+",
			companies: "35K+",
			jobs: "85K+",
			events: "1500+",
			projects: "900+",
		},
		keyAreas: [
			"Mentorship & Coaching",
			"Training & Development",
			"Career Guidance & Counseling",
			"Leadership Development",
			"Change Management",
			"Organizational Development",
			"Community Building",
			"Social Impact & CSR",
		],
		benefits: [
			"Extensive mentorship networks",
			"Leadership development programs",
			"Community building resources",
			"Social impact project opportunities",
			"Professional coaching certifications",
			"Access to development frameworks and tools",
			"Cross-sector partnership opportunities",
			"Recognition and awards programs",
		],
		requirements: [
			"Passion for helping others succeed",
			"Experience in mentoring or enabling roles",
			"Commitment to continuous learning",
			"Collaborative and supportive mindset",
		],
		events: [
			{
				id: "ee-1",
				title: "Leadership Excellence Summit",
				type: "conference",
				date: "2025-07-20",
				time: "10:00",
				duration: "2 days",
				location: "hybrid",
				description: "Developing the next generation of African leaders across all sectors.",
				capacity: 1500,
				registered: 1200,
				status: "upcoming",
			},
		],
		leaders: [
			{
				id: "eel-1",
				name: "Mo Ibrahim",
				position: "Leadership & Governance Advisor",
				company: "Mo Ibrahim Foundation",
				expertise: ["Leadership", "Governance", "African Development"],
				bio: "Philanthropist and business leader dedicated to improving leadership and governance across Africa.",
				achievements: [
					"Founded Mo Ibrahim Foundation",
					"Established Ibrahim Prize for Achievement in African Leadership",
					"Built Celtel into leading African telecom company",
					"Champion of good governance across Africa",
				],
			},
		],
		resources: [
			{
				id: "eer-1",
				title: "Mentorship Excellence Toolkit",
				type: "guide",
				description: "Complete guide to effective mentoring relationships and programs.",
				category: "Mentorship",
				difficulty: "intermediate",
				downloadCount: 25000,
				rating: 4.9,
			},
		],
		successStories: [
			{
				id: "ees-1",
				memberName: "Strive Masiyiwa",
				profession: "Business Leader & Philanthropist",
				company: "Econet Group",
				story: "Through JFAN's enablement network, I've mentored hundreds of young entrepreneurs and supported their business journeys.",
				achievement: "Mentored 500+ entrepreneurs, $100M+ invested in African startups through foundation",
				beforeAfter: {
					before: "Successful businessman focused on own ventures",
					after: "Leading mentor and enabler of African entrepreneurship ecosystem",
				},
				year: "2024",
			},
		],
		partnerships: [
			"African Leadership Academy",
			"Tony Elumelu Foundation",
			"Mastercard Foundation",
			"Bill & Melinda Gates Foundation",
			"African Management Institute",
		],
		initiatives: [
			{
				id: "eei-1",
				title: "1M Mentors Initiative",
				description: "Creating a network of 1 million mentors to support African professionals and entrepreneurs.",
				status: "active",
				impact: "250K+ mentoring relationships established",
				participants: "500K+",
				startDate: "2021-01-01",
			},
		],
		futureGoals: [
			"Establish mentorship programs in every African university",
			"Create leadership development pipeline for 100K+ future leaders",
			"Build Africa's largest professional coaching network",
			"Launch African Leadership Excellence Awards",
		],
	},
];

export const getCommunityBySlug = (slug: string): CommunityData | undefined => {
	return communitiesData.find((community) => community.slug === slug);
};

export const getCommunityStats = () => {
	const totalMembers = communitiesData.reduce((sum, community) => {
		const memberCount = parseFloat(community.stats.members.replace(/[^0-9.]/g, ""));
		const multiplier = community.stats.members.includes("M") ? 1000000 : community.stats.members.includes("K") ? 1000 : 1;
		return sum + memberCount * multiplier;
	}, 0);

	const totalProfessionals = communitiesData.reduce((sum, community) => {
		const profCount = parseFloat(community.stats.professionals.replace(/[^0-9.]/g, ""));
		const multiplier = community.stats.professionals.includes("K") ? 1000 : 1;
		return sum + profCount * multiplier;
	}, 0);

	const totalEvents = communitiesData.reduce((sum, community) => {
		return sum + parseInt(community.stats.events.replace(/[^0-9]/g, ""));
	}, 0);

	const totalJobs = communitiesData.reduce((sum, community) => {
		const jobCount = parseFloat(community.stats.jobs.replace(/[^0-9.]/g, ""));
		const multiplier = community.stats.jobs.includes("K") ? 1000 : 1;
		return sum + jobCount * multiplier;
	}, 0);

	return {
		totalMembers: `${(totalMembers / 1000000).toFixed(1)}M+`,
		totalProfessionals: `${Math.round(totalProfessionals / 1000)}K+`,
		totalEvents: `${totalEvents}+`,
		totalJobs: `${Math.round(totalJobs / 1000)}K+`,
		totalCommunities: communitiesData.length,
	};
};
