// lib/regionsData.ts
import {
	MapPin,
	Phone,
	Mail,
	Users,
	Building,
	Briefcase,
	GraduationCap,
	Rocket,
	Handshake,
	TrendingUp,
	Award,
	Globe,
	Calendar,
	Clock,
	Target,
	Zap,
	CheckCircle,
	DollarSign,
	BarChart3,
	Heart,
	Shield,
	Lightbulb,
} from "lucide-react";
import { CoreValue, Initiative, Milestone, Partnership, RegionalData, Statistic, TeamMember } from "../types";

export const regionsData: RegionalData[] = [
	{
		name: "North Africa",
		slug: "north-africa",
		headquarters: "Cairo, Egypt",
		color: "#10B981",
		establishedYear: "2020",
		description:
			"Gateway between Africa, Europe, and the Middle East with rich cultural heritage and rapidly growing tech ecosystem. North Africa serves as JFAN's strategic bridge connecting African talent with Mediterranean and European opportunities.",
		countries: ["Algeria", "Egypt", "Libya", "Morocco", "Sudan", "Tunisia"],
		population: "246 million",
		gdp: "$785 billion",
		languages: ["Arabic", "French", "English", "Berber"],
		currencies: ["Egyptian Pound", "Moroccan Dirham", "Tunisian Dinar", "Libyan Dinar"],
		timeZones: ["UTC+1", "UTC+2"],
		keyIndustries: ["Oil & Gas", "Tourism", "Agriculture", "Technology", "Textiles", "Mining"],
		stats: {
			members: "2.5M+",
			companies: "45K+",
			jobs: "125K+",
			universities: "180+",
			startups: "8.5K+",
			partnerships: "2.2K+",
		},
		office: {
			city: "Cairo",
			address: "Nile City Towers, North Tower, Floor 35, 2005A Corniche El Nil, Cairo, Egypt",
			phone: "+20 2 2461 9000",
			email: "north-africa@jfan.tech",
		},
		director: {
			id: "dir-north",
			name: "Dr. Amina Hassan",
			position: "Regional Director - North Africa",
			bio: "Leading North Africa operations with over 15 years of experience in international development, technology innovation, and cross-cultural business development.",
			experience: "15+ years in development and tech",
			education: "PhD in Economics, Cairo University; MBA, INSEAD",
			achievements: [
				"Launched 50+ successful tech initiatives across MENA region",
				"Former World Bank consultant on digital transformation",
				"Built partnerships with 200+ regional organizations",
				"Fluent in Arabic, English, French, and Spanish",
			],
			email: "amina.hassan@jfan.tech",
		},
		programs: [
			{
				id: "na-tech-hub",
				title: "North Africa Tech Hub Initiative",
				description:
					"Creating innovation centers in major cities to foster tech entrepreneurship and digital skills development.",
				focus: ["Technology", "Innovation", "Entrepreneurship", "Digital Skills"],
				status: "active",
				budget: "$12M",
				beneficiaries: "50K+ professionals",
				partners: ["African Development Bank", "EU Digital Innovation Hub"],
				startDate: "2022-01",
			},
			{
				id: "na-women-tech",
				title: "Women in Technology Program",
				description: "Empowering women in North Africa through technology training, mentorship, and funding opportunities.",
				focus: ["Gender Equality", "Technology", "Leadership"],
				status: "active",
				budget: "$5M",
				beneficiaries: "15K+ women",
				startDate: "2021-06",
			},
			{
				id: "na-youth-employment",
				title: "Youth Employment Initiative",
				description: "Addressing youth unemployment through skills training and job placement programs.",
				focus: ["Youth Development", "Skills Training", "Job Placement"],
				status: "active",
				beneficiaries: "75K+ youth",
				startDate: "2020-09",
			},
		],
		successStories: [
			{
				id: "story-na-1",
				name: "Fatima Al-Rashid",
				profession: "Software Engineer",
				country: "Egypt",
				story: "Through JFAN's tech program, I transitioned from teaching to software development and now lead a team of 20 engineers at a major fintech company.",
				achievement: "Lead Engineer at Cairo Fintech, managing $50M+ in transactions",
				year: "2023",
			},
			{
				id: "story-na-2",
				name: "Omar Benali",
				profession: "Entrepreneur",
				country: "Morocco",
				story: "JFAN connected me with investors and mentors who helped me build Morocco's first sustainable agriculture tech platform.",
				achievement: "Founded AgriTech Morocco, serving 10K+ farmers",
				year: "2024",
			},
		],
		opportunities: {
			trending: ["Renewable Energy", "Fintech", "E-commerce", "Digital Marketing"],
			emerging: ["AI/ML Engineering", "Blockchain Development", "Green Technology", "EdTech"],
			highDemand: ["Software Development", "Digital Marketing", "Project Management", "Data Analysis"],
		},
		challenges: ["Youth unemployment rates", "Digital skills gap", "Limited access to funding", "Regulatory barriers for startups"],
		initiatives: [
			"Digital Skills Academy with 100+ courses",
			"Cross-border startup accelerator program",
			"Women entrepreneurship fund ($10M allocated)",
			"Green jobs initiative targeting renewable energy sector",
		],
		futureGoals: [
			"Reach 5M+ members by 2026",
			"Establish tech hubs in all 6 countries",
			"Create 500K+ new job opportunities",
			"Launch regional venture capital fund",
		],
	},
	{
		name: "West Africa",
		slug: "west-africa",
		headquarters: "Lagos, Nigeria",
		color: "#F59E0B",
		establishedYear: "2020",
		description:
			"Africa's most populous region and economic powerhouse, leading in fintech innovation, creative industries, and entrepreneurial spirit. Home to over 400 million people and the continent's largest economy.",
		countries: [
			"Nigeria",
			"Ghana",
			"Senegal",
			"Mali",
			"Burkina Faso",
			"Niger",
			"Guinea",
			"Sierra Leone",
			"Liberia",
			"Ivory Coast",
			"Gambia",
			"Guinea-Bissau",
			"Cape Verde",
			"Mauritania",
			"Togo",
			"Benin",
		],
		population: "411 million",
		gdp: "$1.2 trillion",
		languages: ["English", "French", "Portuguese", "Hausa", "Yoruba", "Igbo", "Wolof"],
		currencies: ["Nigerian Naira", "Ghana Cedi", "CFA Franc", "Cape Verdean Escudo"],
		timeZones: ["UTC+0", "UTC+1"],
		keyIndustries: ["Technology", "Oil & Gas", "Agriculture", "Finance", "Creative Arts", "Manufacturing"],
		stats: {
			members: "8.2M+",
			companies: "120K+",
			jobs: "380K+",
			universities: "450+",
			startups: "25K+",
			partnerships: "5.8K+",
		},
		office: {
			city: "Lagos",
			address: "Eko Tower, 1415 Adetokunbo Ademola Street, Victoria Island, Lagos, Nigeria",
			phone: "+234 1 271 0000",
			email: "west-africa@jfan.tech",
		},
		director: {
			id: "dir-west",
			name: "Prof. Kwame Asante",
			position: "Regional Director - West Africa",
			bio: "Driving fintech innovation and creative industries development across West Africa's 16 countries with deep expertise in technology entrepreneurship and regional integration.",
			experience: "18+ years in tech and finance",
			education: "PhD in Computer Science, University of Ghana; Executive MBA, Lagos Business School",
			achievements: [
				"Built 3 successful fintech companies valued at $200M+",
				"Advised governments on digital transformation policies",
				"Published 50+ research papers on African technology",
				"Mentor to 500+ tech entrepreneurs across the region",
			],
			email: "kwame.asante@jfan.tech",
		},
		programs: [
			{
				id: "wa-fintech-hub",
				title: "West Africa Fintech Accelerator",
				description: "Supporting fintech startups across West Africa with funding, mentorship, and market access.",
				focus: ["Fintech", "Financial Inclusion", "Innovation"],
				status: "active",
				budget: "$25M",
				beneficiaries: "200+ startups",
				partners: ["Mastercard Foundation", "African Development Bank"],
				startDate: "2021-03",
			},
			{
				id: "wa-creative-economy",
				title: "Creative Industries Development Program",
				description:
					"Empowering creators in music, film, fashion, and digital arts through skills development and market connections.",
				focus: ["Creative Arts", "Digital Media", "Entertainment"],
				status: "active",
				budget: "$15M",
				beneficiaries: "100K+ creatives",
				startDate: "2020-11",
			},
		],
		successStories: [
			{
				id: "story-wa-1",
				name: "Adaora Okafor",
				profession: "Fintech CEO",
				country: "Nigeria",
				story: "JFAN's accelerator program helped me scale my payment platform from Nigeria to 8 West African countries.",
				achievement: "CEO of PayWest, processing $500M+ annually",
				year: "2023",
			},
			{
				id: "story-wa-2",
				name: "Kofi Mensah",
				profession: "Film Director",
				country: "Ghana",
				story: "Through JFAN's creative program, I connected with international distributors and my films now stream globally.",
				achievement: "Films distributed in 25+ countries, 10M+ viewers",
				year: "2024",
			},
		],
		opportunities: {
			trending: ["Fintech", "E-commerce", "AgriTech", "Creative Content", "Mobile Apps"],
			emerging: ["Blockchain", "AI/ML", "IoT", "Cybersecurity", "EdTech"],
			highDemand: ["Software Engineers", "Digital Marketers", "Financial Analysts", "Content Creators"],
		},
		challenges: [
			"Infrastructure limitations",
			"Access to international markets",
			"Talent retention and brain drain",
			"Regulatory harmonization across countries",
		],
		initiatives: [
			"Regional startup fund with $100M capital",
			"Cross-border e-commerce platform",
			"Creative industries export promotion program",
			"Tech talent exchange program between countries",
		],
		futureGoals: [
			"Become Africa's leading tech hub",
			"Create 1M+ jobs in creative industries",
			"Establish fintech regulatory sandboxes in all countries",
			"Launch West Africa's first unicorn incubator",
		],
	},
	{
		name: "East Africa",
		slug: "east-africa",
		headquarters: "Nairobi, Kenya",
		color: "#8B5CF6",
		establishedYear: "2020",
		description:
			"Hub of innovation and entrepreneurship with strong agricultural base and growing tech startup ecosystem. Known for mobile money innovation and coffee exports, East Africa is rapidly becoming a technology and innovation center.",
		countries: ["Kenya", "Tanzania", "Uganda", "Rwanda", "Ethiopia", "Burundi", "South Sudan", "Somalia", "Eritrea", "Djibouti"],
		population: "445 million",
		gdp: "$420 billion",
		languages: ["English", "Swahili", "Amharic", "Kinyarwanda", "French", "Arabic"],
		currencies: ["Kenyan Shilling", "Tanzanian Shilling", "Ugandan Shilling", "Rwandan Franc", "Ethiopian Birr"],
		timeZones: ["UTC+3"],
		keyIndustries: ["Agriculture", "Tourism", "Technology", "Manufacturing", "Coffee Export", "Textiles"],
		stats: {
			members: "3.8M+",
			companies: "65K+",
			jobs: "190K+",
			universities: "280+",
			startups: "12K+",
			partnerships: "3.4K+",
		},
		office: {
			city: "Nairobi",
			address: "I&M Bank Tower, 2nd Ngong Avenue, Upper Hill, Nairobi, Kenya",
			phone: "+254 20 322 8000",
			email: "east-africa@jfan.tech",
		},
		director: {
			id: "dir-east",
			name: "Dr. Grace Wanjiku",
			position: "Regional Director - East Africa",
			bio: "Fostering entrepreneurship and agricultural innovation in East Africa's growing tech ecosystem with expertise in sustainable development and digital transformation.",
			experience: "12+ years in development and innovation",
			education: "PhD in Agricultural Economics, University of Nairobi; MSc in Development Studies, Oxford",
			achievements: [
				"Led $50M+ agricultural innovation projects",
				"Founded 2 successful agritech startups",
				"Advisor to 5 East African governments on digital agriculture",
				"Published expert on sustainable development in Africa",
			],
			email: "grace.wanjiku@jfan.tech",
		},
		programs: [
			{
				id: "ea-agritech-innovation",
				title: "AgriTech Innovation Program",
				description: "Leveraging technology to modernize agriculture and improve food security across East Africa.",
				focus: ["Agriculture", "Technology", "Food Security", "Sustainability"],
				status: "active",
				budget: "$20M",
				beneficiaries: "500K+ farmers",
				partners: ["USAID", "World Food Programme", "Bill & Melinda Gates Foundation"],
				startDate: "2021-01",
			},
			{
				id: "ea-mobile-money",
				title: "Digital Financial Services Expansion",
				description: "Building on East Africa's mobile money success to expand financial inclusion.",
				focus: ["Financial Inclusion", "Mobile Technology", "Rural Development"],
				status: "active",
				budget: "$8M",
				beneficiaries: "2M+ users",
				startDate: "2020-08",
			},
		],
		successStories: [
			{
				id: "story-ea-1",
				name: "Samuel Kiprotich",
				profession: "AgriTech Entrepreneur",
				country: "Kenya",
				story: "JFAN helped me develop a mobile app that connects smallholder farmers directly with buyers, eliminating middlemen.",
				achievement: "FarmConnect app serving 50K+ farmers, $10M+ in transactions",
				year: "2023",
			},
			{
				id: "story-ea-2",
				name: "Aisha Mohammed",
				profession: "Mobile Developer",
				country: "Tanzania",
				story: "Through JFAN's tech program, I learned mobile development and now build apps for financial services across East Africa.",
				achievement: "Senior Developer at leading fintech, apps used by 1M+ people",
				year: "2024",
			},
		],
		opportunities: {
			trending: ["AgriTech", "Mobile Money", "Tourism Tech", "Healthcare Tech", "Logistics"],
			emerging: ["Climate Tech", "EdTech", "Supply Chain Tech", "Renewable Energy"],
			highDemand: ["Mobile Developers", "Agricultural Engineers", "Data Scientists", "Tourism Specialists"],
		},
		challenges: [
			"Rural connectivity and infrastructure",
			"Climate change adaptation",
			"Skills gap in emerging technologies",
			"Access to growth capital",
		],
		initiatives: [
			"East Africa Innovation Challenge with $15M in prizes",
			"Rural connectivity expansion program",
			"Climate-smart agriculture initiative",
			"Regional startup visa program",
		],
		futureGoals: [
			"Transform agriculture through technology",
			"Achieve universal financial inclusion",
			"Become carbon-neutral innovation hub",
			"Create 500K+ green jobs by 2027",
		],
	},
	{
		name: "Central Africa",
		slug: "central-africa",
		headquarters: "Bangui, Central African Republic",
		color: "#EC4899",
		establishedYear: "2021",
		description:
			"Resource-rich region with vast mineral wealth and growing focus on sustainable development initiatives. Central Africa is positioning itself as a leader in sustainable resource management and environmental conservation.",
		countries: [
			"Central African Republic",
			"Cameroon",
			"Chad",
			"Democratic Republic of Congo",
			"Republic of Congo",
			"Equatorial Guinea",
			"Gabon",
			"São Tomé and Príncipe",
		],
		population: "175 million",
		gdp: "$180 billion",
		languages: ["French", "English", "Portuguese", "Sango", "Lingala", "Local Languages"],
		currencies: ["CFA Franc", "Congolese Franc"],
		timeZones: ["UTC+1"],
		keyIndustries: ["Mining", "Forestry", "Oil & Gas", "Agriculture", "Fishing", "Tourism"],
		stats: {
			members: "1.9M+",
			companies: "28K+",
			jobs: "85K+",
			universities: "120+",
			startups: "3.5K+",
			partnerships: "1.8K+",
		},
		office: {
			city: "Bangui",
			address: "Avenue de l'Indépendance, Quartier Centrafrique, Bangui, Central African Republic",
			phone: "+236 21 61 0000",
			email: "central-africa@jfan.tech",
		},
		director: {
			id: "dir-central",
			name: "Mr. Jean-Baptiste Moukoko",
			position: "Regional Director - Central Africa",
			bio: "Promoting sustainable development and resource management across Central Africa's diverse economies with focus on environmental conservation and community development.",
			experience: "14+ years in sustainable development",
			education: "MSc in Environmental Management, University of Yaoundé; Executive Certificate in Sustainable Development, Columbia University",
			achievements: [
				"Led $100M+ sustainable development programs",
				"Expert in natural resource management",
				"Advisor to regional governments on environmental policy",
				"Champion of community-based conservation initiatives",
			],
			email: "jean.moukoko@jfan.tech",
		},
		programs: [
			{
				id: "ca-sustainable-mining",
				title: "Sustainable Mining Initiative",
				description: "Promoting responsible mining practices and local community benefit from mineral resources.",
				focus: ["Mining", "Sustainability", "Community Development"],
				status: "active",
				budget: "$30M",
				beneficiaries: "200K+ community members",
				partners: ["World Bank", "African Union", "Extractive Industries Transparency Initiative"],
				startDate: "2021-06",
			},
			{
				id: "ca-forest-conservation",
				title: "Congo Basin Forest Conservation Program",
				description: "Protecting the world's second-largest rainforest while creating sustainable livelihoods.",
				focus: ["Environmental Conservation", "Sustainable Livelihoods", "Climate Change"],
				status: "active",
				budget: "$45M",
				beneficiaries: "1M+ forest-dependent communities",
				startDate: "2021-03",
			},
		],
		successStories: [
			{
				id: "story-ca-1",
				name: "Marie Ngozi",
				profession: "Environmental Consultant",
				country: "Democratic Republic of Congo",
				story: "JFAN's sustainable development program helped me establish an environmental consulting firm that now advises major mining companies.",
				achievement: "Founded EcoConsult DRC, working with 20+ international mining companies",
				year: "2023",
			},
			{
				id: "story-ca-2",
				name: "Paul Obame",
				profession: "Sustainable Agriculture Specialist",
				country: "Gabon",
				story: "Through JFAN, I developed agroforestry techniques that help farmers increase yields while preserving forest cover.",
				achievement: "Agroforestry methods adopted by 5K+ farmers, 50% yield increase",
				year: "2024",
			},
		],
		opportunities: {
			trending: ["Sustainable Mining", "Forestry Management", "Eco-Tourism", "Renewable Energy"],
			emerging: ["Carbon Trading", "Conservation Technology", "Sustainable Agriculture", "Green Infrastructure"],
			highDemand: ["Environmental Engineers", "Forestry Specialists", "Mining Engineers", "Conservation Experts"],
		},
		challenges: [
			"Infrastructure development needs",
			"Balancing development with conservation",
			"Limited access to international markets",
			"Skills development in remote areas",
		],
		initiatives: [
			"Central Africa Green Economy Fund ($50M)",
			"Regional conservation technology center",
			"Sustainable livelihoods training program",
			"Cross-border environmental monitoring system",
		],
		futureGoals: [
			"Become leader in sustainable resource management",
			"Establish carbon-neutral development model",
			"Create 200K+ green jobs by 2026",
			"Protect 50% of Congo Basin forest",
		],
	},
	{
		name: "Southern Africa",
		slug: "southern-africa",
		headquarters: "Johannesburg, South Africa",
		color: "#06B6D4",
		establishedYear: "2020",
		description:
			"Industrial and financial hub of Africa with advanced infrastructure and established business networks. Southern Africa combines mature markets with emerging opportunities in technology and renewable energy.",
		countries: [
			"South Africa",
			"Botswana",
			"Zimbabwe",
			"Zambia",
			"Namibia",
			"Lesotho",
			"Eswatini",
			"Malawi",
			"Mozambique",
			"Madagascar",
			"Mauritius",
			"Seychelles",
			"Comoros",
		],
		population: "174 million",
		gdp: "$750 billion",
		languages: ["English", "Afrikaans", "Portuguese", "Zulu", "Xhosa", "Setswana", "French"],
		currencies: ["South African Rand", "Botswana Pula", "Namibian Dollar", "Mauritian Rupee"],
		timeZones: ["UTC+2"],
		keyIndustries: ["Mining", "Finance", "Technology", "Tourism", "Manufacturing", "Agriculture"],
		stats: {
			members: "4.1M+",
			companies: "85K+",
			jobs: "245K+",
			universities: "320+",
			startups: "18K+",
			partnerships: "4.5K+",
		},
		office: {
			city: "Johannesburg",
			address: "Carlton Centre, 150 Commissioner Street, Marshalltown, Johannesburg, South Africa",
			phone: "+27 11 834 0000",
			email: "southern-africa@jfan.tech",
		},
		director: {
			id: "dir-south",
			name: "Ms. Nomsa Ndlovu",
			position: "Regional Director - Southern Africa",
			bio: "Leading financial services and industrial development initiatives across Southern Africa's established markets with expertise in capital markets and technology innovation.",
			experience: "16+ years in finance and technology",
			education: "MBA in Finance, University of Cape Town; BCom Honors, University of the Witwatersrand",
			achievements: [
				"Former senior executive at major African bank",
				"Led $500M+ technology investment initiatives",
				"Board member of 3 major African corporations",
				"Expert in African capital markets development",
			],
			email: "nomsa.ndlovu@jfan.tech",
		},
		programs: [
			{
				id: "sa-fintech-innovation",
				title: "Southern Africa FinTech Innovation Hub",
				description: "Leveraging the region's financial expertise to drive fintech innovation across Africa.",
				focus: ["Financial Technology", "Capital Markets", "Investment"],
				status: "active",
				budget: "$35M",
				beneficiaries: "300+ fintech startups",
				partners: ["Johannesburg Stock Exchange", "Standard Bank", "Nedbank"],
				startDate: "2020-10",
			},
			{
				id: "sa-renewable-energy",
				title: "Renewable Energy Skills Program",
				description: "Training professionals for the transition to renewable energy across Southern Africa.",
				focus: ["Renewable Energy", "Green Skills", "Climate Action"],
				status: "active",
				budget: "$25M",
				beneficiaries: "50K+ professionals",
				startDate: "2021-09",
			},
		],
		successStories: [
			{
				id: "story-sa-1",
				name: "Thabo Mthembu",
				profession: "FinTech Entrepreneur",
				country: "South Africa",
				story: "JFAN's innovation hub connected me with investors and helped scale my mobile lending platform across 5 Southern African countries.",
				achievement: "CEO of LendFast, $100M+ in loans facilitated",
				year: "2023",
			},
			{
				id: "story-sa-2",
				name: "Chipo Mukamuri",
				profession: "Renewable Energy Engineer",
				country: "Zimbabwe",
				story: "Through JFAN's renewable energy program, I gained skills that helped me design solar systems now powering 200+ rural communities.",
				achievement: "Lead Engineer at SolarAfrica, 50MW+ of installations",
				year: "2024",
			},
		],
		opportunities: {
			trending: ["FinTech", "Renewable Energy", "Mining Technology", "Tourism", "Agriculture"],
			emerging: ["Green Hydrogen", "Carbon Markets", "Digital Banking", "Sustainable Mining"],
			highDemand: ["Software Engineers", "Financial Analysts", "Renewable Energy Engineers", "Data Scientists"],
		},
		challenges: [
			"Energy security and load shedding",
			"Skills migration to other regions",
			"Economic inequality",
			"Infrastructure modernization needs",
		],
		initiatives: [
			"Southern Africa Venture Capital Fund ($200M)",
			"Regional renewable energy training centers",
			"Cross-border fintech regulatory framework",
			"Skills retention and development program",
		],
		futureGoals: [
			"Become Africa's financial technology hub",
			"Lead continental renewable energy transition",
			"Create 750K+ high-skilled jobs by 2026",
			"Establish regional innovation corridor",
		],
	},
	{
		name: "Diaspora Region",
		slug: "diaspora",
		headquarters: "Global Network",
		color: "#6366F1",
		establishedYear: "2020",
		description:
			"Connecting African professionals worldwide, facilitating knowledge transfer and investment opportunities. The diaspora represents Africa's global talent network with immense potential for continental development.",
		countries: ["Global Network - 195+ Countries"],
		population: "140+ million (estimated)",
		gdp: "$500+ billion (remittances & investments)",
		languages: ["Multi-lingual", "English", "French", "Portuguese", "Spanish", "German", "Arabic"],
		currencies: ["Multi-currency (USD, EUR, GBP, CAD, AUD, etc.)"],
		timeZones: ["Global - All Time Zones"],
		keyIndustries: ["Technology", "Healthcare", "Education", "Consulting", "Finance", "Research"],
		stats: {
			members: "2.8M+",
			companies: "95K+",
			jobs: "200K+",
			universities: "500+ partnerships",
			startups: "15K+",
			partnerships: "8.2K+",
		},
		office: {
			city: "Virtual Headquarters",
			address: "Global Digital Hub - Multiple Time Zone Coverage",
			phone: "+1 (555) JFAN-GLOBAL",
			email: "diaspora@jfan.tech",
		},
		director: {
			id: "dir-diaspora",
			name: "Dr. Chidi Okonkwo",
			position: "Global Diaspora Director",
			bio: "Connecting African professionals worldwide and facilitating knowledge transfer and investment opportunities with extensive experience in international business and diaspora engagement.",
			experience: "20+ years in international business",
			education: "PhD in International Business, Harvard Business School; MBA, Wharton School",
			achievements: [
				"Built 5 successful international businesses",
				"Facilitated $2B+ in diaspora investments to Africa",
				"Advisor to multiple African governments on diaspora policy",
				"Founded 3 major African diaspora organizations",
			],
			email: "chidi.okonkwo@jfan.tech",
		},
		programs: [
			{
				id: "diaspora-investment-fund",
				title: "Diaspora Investment Fund",
				description: "Mobilizing African diaspora capital for strategic investments in continental development projects.",
				focus: ["Investment", "Diaspora Engagement", "Economic Development"],
				status: "active",
				budget: "$500M",
				beneficiaries: "10K+ investors, 500+ projects",
				partners: ["African Development Bank", "World Bank IFC", "Diaspora investment networks"],
				startDate: "2020-12",
			},
			{
				id: "knowledge-transfer-program",
				title: "Global Knowledge Transfer Initiative",
				description: "Connecting diaspora expertise with African development needs through mentorship and consulting.",
				focus: ["Knowledge Transfer", "Mentorship", "Skills Development"],
				status: "active",
				budget: "$15M",
				beneficiaries: "100K+ mentees",
				startDate: "2021-02",
			},
		],
		successStories: [
			{
				id: "story-diaspora-1",
				name: "Dr. Kofi Asante",
				profession: "Tech Executive",
				country: "USA (Ghana origin)",
				story: "Through JFAN's diaspora network, I returned to Ghana to establish a tech hub that has now created 500+ jobs and trained 5,000+ developers.",
				achievement: "Founded Ghana Tech Hub, $50M+ in investments raised",
				year: "2023",
			},
			{
				id: "story-diaspora-2",
				name: "Amina Salim",
				profession: "Healthcare Consultant",
				country: "Canada (Somalia origin)",
				story: "JFAN helped me connect with healthcare systems across East Africa to implement telemedicine solutions serving 100K+ patients.",
				achievement: "CEO of AfriHealth Telemedicine, serving 15 African countries",
				year: "2024",
			},
		],
		opportunities: {
			trending: ["Diaspora Investment", "Remote Work", "Consulting", "Technology Transfer", "Education"],
			emerging: ["Impact Investing", "Digital Nomadism", "Cross-border E-commerce", "Virtual Services"],
			highDemand: ["Investment Advisors", "Technology Consultants", "Healthcare Specialists", "Education Experts"],
		},
		challenges: [
			"Coordination across time zones and cultures",
			"Regulatory compliance in multiple jurisdictions",
			"Building trust for investment opportunities",
			"Facilitating effective knowledge transfer",
		],
		initiatives: [
			"Global African Professional Network (500K+ members)",
			"Diaspora bond program for infrastructure financing",
			"Virtual mentorship platform connecting 50K+ pairs",
			"Annual Global African Diaspora Conference",
		],
		futureGoals: [
			"Mobilize $10B+ in diaspora investments by 2026",
			"Connect 5M+ diaspora professionals",
			"Establish diaspora business hubs in 20+ global cities",
			"Create seamless Africa-diaspora business corridor",
		],
	},
];

export const getRegionBySlug = (slug: string): RegionalData | undefined => {
	return regionsData.find((region) => region.slug === slug);
};

export const getRegionStats = () => {
	const totalMembers = regionsData.reduce((sum, region) => {
		const memberCount = parseFloat(region.stats.members.replace(/[^0-9.]/g, ""));
		const multiplier = region.stats.members.includes("M") ? 1000000 : region.stats.members.includes("K") ? 1000 : 1;
		return sum + memberCount * multiplier;
	}, 0);

	const totalCompanies = regionsData.reduce((sum, region) => {
		const companyCount = parseFloat(region.stats.companies.replace(/[^0-9.]/g, ""));
		const multiplier = region.stats.companies.includes("K") ? 1000 : 1;
		return sum + companyCount * multiplier;
	}, 0);

	const totalJobs = regionsData.reduce((sum, region) => {
		const jobCount = parseFloat(region.stats.jobs.replace(/[^0-9.]/g, ""));
		const multiplier = region.stats.jobs.includes("K") ? 1000 : 1;
		return sum + jobCount * multiplier;
	}, 0);

	return {
		totalMembers: `${(totalMembers / 1000000).toFixed(1)}M+`,
		totalCompanies: `${Math.round(totalCompanies / 1000)}K+`,
		totalJobs: `${Math.round(totalJobs / 1000)}K+`,
		totalCountries: regionsData.reduce((sum, region) => sum + region.countries.length, 0) - 194, // Remove duplicated global count
		totalRegions: regionsData.length,
	};
};

export const aboutStatistics: Statistic[] = [
	{
		value: "22M+",
		label: "Active Members",
		description: "Professionals across Africa and diaspora",
		icon: <Users className="w-8 h-8" />,
	},
	{
		value: "55",
		label: "Countries",
		description: "Complete African continental coverage",
		icon: <Globe className="w-8 h-8" />,
	},
	{
		value: "438K+",
		label: "Partner Companies",
		description: "Organizations actively recruiting",
		icon: <Building className="w-8 h-8" />,
	},
	{
		value: "1.2M+",
		label: "Job Opportunities",
		description: "Active positions across all sectors",
		icon: <Target className="w-8 h-8" />,
	},
	{
		value: "98%",
		label: "Success Rate",
		description: "Members finding suitable opportunities",
		icon: <Award className="w-8 h-8" />,
	},
	{
		value: "6",
		label: "Regional Hubs",
		description: "Strategic locations across Africa",
		icon: <TrendingUp className="w-8 h-8" />,
	},
];

export const coreValues: CoreValue[] = [
	{
		icon: <Users className="w-8 h-8" />,
		title: "Unity",
		description: "Bringing together diverse African communities under one unified platform for collective growth and development.",
		principles: [
			"Pan-African collaboration",
			"Cultural diversity celebration",
			"Inclusive community building",
			"Cross-border partnerships",
		],
	},
	{
		icon: <Award className="w-8 h-8" />,
		title: "Excellence",
		description: "Committed to delivering exceptional service and maintaining the highest standards in everything we do.",
		principles: ["Quality-first approach", "Continuous improvement", "Professional standards", "Service excellence"],
	},
	{
		icon: <Lightbulb className="w-8 h-8" />,
		title: "Innovation",
		description: "Embracing cutting-edge technologies and creative solutions to solve Africa's professional challenges.",
		principles: ["Technology advancement", "Creative problem-solving", "Future-ready solutions", "Digital transformation"],
	},
	{
		icon: <Shield className="w-8 h-8" />,
		title: "Integrity",
		description: "Operating with transparency, honesty, and ethical practices in all our interactions and partnerships.",
		principles: ["Transparent operations", "Ethical business practices", "Honest communication", "Trustworthy partnerships"],
	},
	{
		icon: <Heart className="w-8 h-8" />,
		title: "Empowerment",
		description: "Enabling individuals and communities to unlock their full potential and achieve sustainable success.",
		principles: ["Skill development", "Capacity building", "Economic empowerment", "Community upliftment"],
	},
	{
		icon: <TrendingUp className="w-8 h-8" />,
		title: "Growth",
		description: "Fostering continuous learning, development, and expansion opportunities for all members.",
		principles: ["Professional development", "Career advancement", "Network expansion", "Personal growth"],
	},
];

export const partnerships: Partnership[] = [
	{
		name: "IHRC",
		full: "International Human Rights Commission",
		description: "Ensuring fair labor practices and human rights protection across all JFAN operations.",
		region: "Africa Region HQ",
		focus: "Human Rights & Labor Standards",
	},
	{
		name: "PAOSMI",
		full: "Pan African Alliance of Small & Medium Industries",
		description: "Supporting SME development and entrepreneurship across the African continent.",
		region: "Continental Network",
		focus: "SME Development & Entrepreneurship",
	},
	{
		name: "AAS",
		full: "African Academy of Science",
		description: "Promoting scientific research, innovation, and evidence-based policy development.",
		region: "Research & Development",
		focus: "Scientific Research & Innovation",
	},
	{
		name: "GISDAAD",
		full: "Global Institute for Sustainable Development",
		description: "Advancing sustainable development goals through advanced analysis and design.",
		region: "Advanced Analysis & Design",
		focus: "Sustainable Development",
	},
];

export const teamMembers: TeamMember[] = [
	{
		id: "dir-north",
		name: "Dr. Amina Hassan",
		position: "Regional Director",
		region: "North Africa",
		bio: "Leading operations across North Africa with over 15 years of experience in international development and technology innovation.",
		email: "amina.hassan@jfan.tech",
	},
	{
		id: "dir-west",
		name: "Prof. Kwame Asante",
		position: "Regional Director",
		region: "West Africa",
		bio: "Driving fintech innovation and creative industries development across West Africa's 16 countries.",
		email: "kwame.asante@jfan.tech",
	},
	{
		id: "dir-east",
		name: "Dr. Grace Wanjiku",
		position: "Regional Director",
		region: "East Africa",
		bio: "Fostering entrepreneurship and agricultural innovation in East Africa's growing tech ecosystem.",
		email: "grace.wanjiku@jfan.tech",
	},
	{
		id: "dir-central",
		name: "Mr. Jean-Baptiste Moukoko",
		position: "Regional Director",
		region: "Central Africa",
		bio: "Promoting sustainable development and resource management across Central Africa's diverse economies.",
		email: "jean.moukoko@jfan.tech",
	},
	{
		id: "dir-south",
		name: "Ms. Nomsa Ndlovu",
		position: "Regional Director",
		region: "Southern Africa",
		bio: "Leading financial services and industrial development initiatives across Southern Africa's established markets.",
		email: "nomsa.ndlovu@jfan.tech",
	},
	{
		id: "dir-diaspora",
		name: "Dr. Chidi Okonkwo",
		position: "Global Diaspora Director",
		region: "Diaspora Network",
		bio: "Connecting African professionals worldwide and facilitating knowledge transfer and investment opportunities.",
		email: "chidi.okonkwo@jfan.tech",
	},
];

export const milestones: Milestone[] = [
	{
		year: "2020",
		title: "JFAN Foundation",
		description: "Established as a response to Africa's need for unified professional networking.",
		impact: "Initial 50,000 members across 10 countries",
	},
	{
		year: "2021",
		title: "Continental Expansion",
		description: "Extended operations to all 55 African countries with regional hub establishment.",
		impact: "Reached 2.5M members and 25,000 partner companies",
	},
	{
		year: "2022",
		title: "Strategic Partnerships",
		description: "Formed key alliances with IHRC, PAOSMI, AAS, and GISDAAD.",
		impact: "Enhanced credibility and expanded service offerings",
	},
	{
		year: "2023",
		title: "Technology Innovation",
		description: "Launched AI-powered job matching and skills assessment platform.",
		impact: "98% job matching success rate achieved",
	},
	{
		year: "2024",
		title: "Global Recognition",
		description: "Recognized as Africa's leading professional network by international bodies.",
		impact: "22M+ active members, 438K+ partner companies",
	},
];

export const initiatives: Initiative[] = [
	{
		title: "NTS Crowd-Donor Community Portal",
		description: "Revolutionary crowdfunding platform enabling individual and corporate donation accounts for professional development.",
		status: "active",
		impact: "$12M+ raised for skill development programs",
		partners: ["African Development Bank", "World Bank Group"],
	},
	{
		title: "Digital Skills Academy",
		description: "Comprehensive online training platform offering courses in emerging technologies and digital skills.",
		status: "active",
		impact: "500K+ professionals trained",
		partners: ["Microsoft", "Google", "IBM"],
	},
	{
		title: "Women in Tech Initiative",
		description: "Empowering African women in technology through mentorship, funding, and networking opportunities.",
		status: "active",
		impact: "75K+ women supported, 40% increase in tech participation",
	},
	{
		title: "Youth Entrepreneurship Program",
		description: "Supporting young African entrepreneurs with business development resources and funding access.",
		status: "active",
		impact: "25K+ young entrepreneurs supported, 15,000 businesses launched",
	},
	{
		title: "Green Jobs Initiative",
		description: "Promoting sustainable employment opportunities in renewable energy and environmental sectors.",
		status: "planned",
		impact: "Target: 100K green jobs by 2026",
	},
	{
		title: "Rural Development Program",
		description: "Extending JFAN services to rural communities through mobile technology and local partnerships.",
		status: "active",
		impact: "2M+ rural professionals connected",
	},
];
